

services:
  db:
    image: postgres:16
    container_name: postgres_hotel
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: hotelaria
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - hotel_network

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin_hotel
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hotel.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - hotel_network

volumes:
  db_data:

networks:
  hotel_network:

